package UI;

import UTILS.Auth;
import UTILS.MsgBox;
import java.awt.Desktop;
import java.awt.Dimension;
import java.net.URI;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

public class mainWindows extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form mainMenu
     */
    public mainWindows() {
        initComponents();
        setLocationRelativeTo(null);
        TrangThai();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnChuyenDe = new javax.swing.JButton();
        btnNguoiHoc = new javax.swing.JButton();
        btnKhoaHoc = new javax.swing.JButton();
        btnHocVien = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnHuongDan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblDongHo = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        Desktop = new javax.swing.JDesktopPane();
        mnbMenu = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDangXuat = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniThoat = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mmiChuyenDe = new javax.swing.JMenuItem();
        mmiKhoaHoc = new javax.swing.JMenuItem();
        mmiNguoiHoc = new javax.swing.JMenuItem();
        mmiHocVien = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mmiNhanVien = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniBangDiem = new javax.swing.JMenuItem();
        mniLuongNguoiHoc = new javax.swing.JMenuItem();
        mniDiemChuyenDe = new javax.swing.JMenuItem();
        mniDoanhThu = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();
        mniHuongDan = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mmiGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnDangXuat.setIcon(new javax.swing.ImageIcon("C:\\Users\\FPTSHOP\\OneDrive\\Desktop\\DUANMAU\\ASM_SOF2041_PY00047\\Du_An_Mau\\src\\main\\java\\ICONS\\logout.png")); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);

        btnThoat.setIcon(new javax.swing.ImageIcon("C:\\Users\\FPTSHOP\\OneDrive\\Desktop\\DUANMAU\\ASM_SOF2041_PY00047\\Du_An_Mau\\src\\main\\java\\ICONS\\exit.png")); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setFocusable(false);
        btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnThoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThoat);
        jToolBar1.add(jSeparator3);

        btnChuyenDe.setIcon(new javax.swing.ImageIcon("C:\\Users\\FPTSHOP\\OneDrive\\Desktop\\DUANMAU\\ASM_SOF2041_PY00047\\Du_An_Mau\\src\\main\\java\\ICONS\\ChuyenDe.png")); // NOI18N
        btnChuyenDe.setText("Chuyên đề");
        btnChuyenDe.setFocusable(false);
        btnChuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenDe.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnChuyenDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenDeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChuyenDe);

        btnNguoiHoc.setIcon(new javax.swing.ImageIcon("C:\\Users\\FPTSHOP\\OneDrive\\Desktop\\DUANMAU\\ASM_SOF2041_PY00047\\Du_An_Mau\\src\\main\\java\\ICONS\\NguoiHoc.png")); // NOI18N
        btnNguoiHoc.setText("Người học");
        btnNguoiHoc.setFocusable(false);
        btnNguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoiHoc.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnNguoiHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoiHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNguoiHoc);

        btnKhoaHoc.setIcon(new javax.swing.ImageIcon("C:\\Users\\FPTSHOP\\OneDrive\\Desktop\\DUANMAU\\ASM_SOF2041_PY00047\\Du_An_Mau\\src\\main\\java\\ICONS\\KhoaHoc.png")); // NOI18N
        btnKhoaHoc.setText("Khóa học");
        btnKhoaHoc.setFocusable(false);
        btnKhoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoaHoc.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnKhoaHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhoaHoc);

        btnHocVien.setIcon(new javax.swing.ImageIcon("C:\\Users\\FPTSHOP\\OneDrive\\Desktop\\DUANMAU\\ASM_SOF2041_PY00047\\Du_An_Mau\\src\\main\\java\\ICONS\\HocVien.png")); // NOI18N
        btnHocVien.setText("Học viên");
        btnHocVien.setFocusable(false);
        btnHocVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHocVien.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnHocVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHocVien);
        jToolBar1.add(jSeparator8);

        btnHuongDan.setIcon(new javax.swing.ImageIcon("C:\\Users\\FPTSHOP\\OneDrive\\Desktop\\DUANMAU\\ASM_SOF2041_PY00047\\Du_An_Mau\\src\\main\\java\\ICONS\\HuongDan.png")); // NOI18N
        btnHuongDan.setText("Hướng dẫn");
        btnHuongDan.setFocusable(false);
        btnHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongDan.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongDanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHuongDan);

        jPanel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 45));

        lblDongHo.setText("Đồng hồ");

        lblTrangThai.setText("status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo))
            .addComponent(lblTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        mnbMenu.setName(""); // NOI18N
        mnbMenu.setRequestFocusEnabled(false);

        mnuHeThong.setText("Hệ Thống");

        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);
        mnuHeThong.add(jSeparator4);

        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMatKhau);
        mnuHeThong.add(jSeparator2);

        mniThoat.setText("Thoát");
        mniThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThoatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniThoat);

        mnbMenu.add(mnuHeThong);

        mnuQuanLy.setText("Quản Lý");

        mmiChuyenDe.setText("Chuyên đề");
        mmiChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmiChuyenDeActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mmiChuyenDe);

        mmiKhoaHoc.setText("Khóa học");
        mmiKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmiKhoaHocActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mmiKhoaHoc);

        mmiNguoiHoc.setText("Người học");
        mmiNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmiNguoiHocActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mmiNguoiHoc);

        mmiHocVien.setText("Học viên");
        mmiHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmiHocVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mmiHocVien);
        mnuQuanLy.add(jSeparator5);

        mmiNhanVien.setText("Nhân viên");
        mmiNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmiNhanVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mmiNhanVien);

        mnbMenu.add(mnuQuanLy);

        mnuThongKe.setText("Thống Kê");

        mniBangDiem.setText("Bảng điểm");
        mniBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBangDiemActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniBangDiem);

        mniLuongNguoiHoc.setText("Lượng người học");
        mniLuongNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLuongNguoiHocActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniLuongNguoiHoc);

        mniDiemChuyenDe.setText("Điểm chuyên đề");
        mniDiemChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDiemChuyenDeActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniDiemChuyenDe);

        mniDoanhThu.setText("Doanh thu");
        mniDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhThuActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniDoanhThu);

        mnbMenu.add(mnuThongKe);

        mnuTroGiup.setText("Trợ giúp");

        mniHuongDan.setText("Hướng dẫn sử dụng");
        mniHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHuongDanActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniHuongDan);
        mnuTroGiup.add(jSeparator6);

        mmiGioiThieu.setText("Giới thiệu sản phẩm");
        mmiGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmiGioiThieuActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mmiGioiThieu);

        mnbMenu.add(mnuTroGiup);

        setJMenuBar(mnbMenu);
        mnbMenu.getAccessibleContext().setAccessibleName("");
        mnbMenu.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Thread time = new Thread(this);
        time.start();
    }//GEN-LAST:event_formWindowOpened

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        openDoiMatKhau();
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        KetThuc();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenDeActionPerformed
        openChuyenDe();
    }//GEN-LAST:event_btnChuyenDeActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.dispose();
        openDangXuat();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void mniThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThoatActionPerformed
        KetThuc();
    }//GEN-LAST:event_mniThoatActionPerformed

    private void btnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoiHocActionPerformed
        openNguoiHoc();
    }//GEN-LAST:event_btnNguoiHocActionPerformed

    private void btnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaHocActionPerformed
        openKhoaHoc();
    }//GEN-LAST:event_btnKhoaHocActionPerformed

    private void btnHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocVienActionPerformed
        openHocVien();
    }//GEN-LAST:event_btnHocVienActionPerformed

    private void mmiNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmiNhanVienActionPerformed
        Quan_Ly_Nhan_Vien qlnv = new Quan_Ly_Nhan_Vien();
        Desktop.add(qlnv).setVisible(true);
        Dimension(qlnv);
        qlnv.setVisible(true);
    }//GEN-LAST:event_mmiNhanVienActionPerformed

    private void mniBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBangDiemActionPerformed
        openThongKe(0);
    }//GEN-LAST:event_mniBangDiemActionPerformed

    private void mniLuongNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLuongNguoiHocActionPerformed
        openThongKe(1);
    }//GEN-LAST:event_mniLuongNguoiHocActionPerformed

    private void mniDiemChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDiemChuyenDeActionPerformed
        openThongKe(2);
    }//GEN-LAST:event_mniDiemChuyenDeActionPerformed

    private void mniDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhThuActionPerformed
        if(Auth.isManager() && Auth.isLogin()){
            openThongKe(3);
        } else {
            MsgBox.alert(this, "Bạn Không có quyền truy cập.");
        }
    }//GEN-LAST:event_mniDoanhThuActionPerformed

    private void mmiChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmiChuyenDeActionPerformed
        openChuyenDe();
    }//GEN-LAST:event_mmiChuyenDeActionPerformed

    private void mmiKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmiKhoaHocActionPerformed
        openKhoaHoc();
    }//GEN-LAST:event_mmiKhoaHocActionPerformed

    private void mmiNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmiNguoiHocActionPerformed
        openNguoiHoc();
    }//GEN-LAST:event_mmiNguoiHocActionPerformed

    private void mmiHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmiHocVienActionPerformed
        openHocVien();
    }//GEN-LAST:event_mmiHocVienActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        this.dispose();
        openDangXuat();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mmiGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmiGioiThieuActionPerformed
        if(Auth.isLogin()) {
            GioiThieu DMK = new GioiThieu();
            Desktop.add(DMK).setVisible(true);
            Dimension(DMK);
            DMK.setVisible(true);
        }else {
            MsgBox.alert(this,"Vui lòng đăng nhập.");
        } 
    }//GEN-LAST:event_mmiGioiThieuActionPerformed

    private void mniHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHuongDanActionPerformed
        if(Auth.isLogin()) {
            try {
                Desktop desktop = java.awt.Desktop.getDesktop();
                URI URL = new URI("file:///C:/Users/FPTSHOP/OneDrive/Desktop/DUANMAU/ASM_SOF2041_PY00047/DuAnMauWeb_HuongDanSuDung/index.html");
                desktop.browse(URL);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }else {
            MsgBox.alert(this,"Vui lòng đăng nhập.");
        } 
    }//GEN-LAST:event_mniHuongDanActionPerformed

    private void btnHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongDanActionPerformed
        if(Auth.isLogin()) {
            try {
                Desktop desktop = java.awt.Desktop.getDesktop();
                URI URL = new URI("file:///C:/Users/FPTSHOP/OneDrive/Desktop/DUANMAU/ASM_SOF2041_PY00047/DuAnMauWeb_HuongDanSuDung/index.html");
                desktop.browse(URL);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }else {
            MsgBox.alert(this,"Vui lòng đăng nhập.");
        } 
    }//GEN-LAST:event_btnHuongDanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainWindows main = new mainWindows();
                main.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
                main.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton btnChuyenDe;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHocVien;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnKhoaHoc;
    private javax.swing.JButton btnNguoiHoc;
    private javax.swing.JButton btnThoat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JMenuItem mmiChuyenDe;
    private javax.swing.JMenuItem mmiGioiThieu;
    private javax.swing.JMenuItem mmiHocVien;
    private javax.swing.JMenuItem mmiKhoaHoc;
    private javax.swing.JMenuItem mmiNguoiHoc;
    private javax.swing.JMenuItem mmiNhanVien;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenuItem mniBangDiem;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDiemChuyenDe;
    private javax.swing.JMenuItem mniDoanhThu;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniHuongDan;
    private javax.swing.JMenuItem mniLuongNguoiHoc;
    private javax.swing.JMenuItem mniThoat;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTroGiup;
    // End of variables declaration//GEN-END:variables

    public void openDoiMatKhau() {
        if(Auth.isLogin()) {
            Doi_Mat_Khau DMK = new Doi_Mat_Khau();
            Desktop.add(DMK).setVisible(true);
            Dimension(DMK);
            DMK.setVisible(true);
        }else {
            MsgBox.alert(this,"Vui lòng đăng nhập.");
        } 
    }
    
    public void openDangXuat() {
        Auth.clear();
        openLogin();
    }
    
    public void KetThuc() {
        if(MsgBox.confirm(this, "Bạn muốn kết thúc?")) {
            System.exit(0);
        }
    }
    
    public void openChuyenDe() {
        if(Auth.isLogin()) {
            Quan_Ly_Chuyen_De qlcd = new Quan_Ly_Chuyen_De();
            Desktop.add(qlcd).setVisible(true);
            Dimension(qlcd);
            qlcd.setVisible(true);
        }else {
            MsgBox.alert(this,"Vui lòng đăng nhập.");
        } 
    }
    
    public void openNguoiHoc() {
        if(Auth.isLogin()) {
            Quan_Ly_Nguoi_Hoc qlnh = new Quan_Ly_Nguoi_Hoc();
            Desktop.add(qlnh).setVisible(true);
            Dimension(qlnh);
            qlnh.setVisible(true);
        }else {
            MsgBox.alert(this,"Vui lòng đăng nhập.");
        } 
    }

    public void openKhoaHoc() {
        if(Auth.isLogin()) {
            Quan_Ly_Khoa_Hoc qlkh = new Quan_Ly_Khoa_Hoc();
            Desktop.add(qlkh).setVisible(true);
            Dimension(qlkh);
            qlkh.setVisible(true);
        }else {
            MsgBox.alert(this,"Vui lòng đăng nhập.");
        } 
    }
    
    public void openThongKe(int index) {
        if(Auth.isLogin()) {
            Thong_Ke tk = new Thong_Ke();
            Desktop.add(tk).setVisible(true);
            tk.selectTab(index);
            Dimension(tk);
            tk.setVisible(true);
        }else {
            MsgBox.alert(this,"Vui lòng đăng nhập.");
        } 
    }

    public void openHocVien() {
        if(Auth.isLogin()) {
            Quan_Ly_Hoc_Vien qlhv = new Quan_Ly_Hoc_Vien();
            Desktop.add(qlhv).setVisible(true);
            Dimension(qlhv);
            qlhv.setVisible(true);
        }else {
            MsgBox.alert(this,"Vui lòng đăng nhập.");
        } 
    }
    
    public void TrangThai() {
        if(Auth.isLogin()){
            lblTrangThai.setText(Auth.user.getMaNV()+"-"+Auth.user.getHoTen());
        }else{
            lblTrangThai.setText("Vui lòng đăng nhập!");
        }
    }

    public String Time(){
        Date now = new Date();
        SimpleDateFormat formater = new SimpleDateFormat();
        formater.applyPattern("hh:mm:ss a");
        String s = formater.format(now);
        return s;
    };

    public void run() {
        while(true){
            String time = Time();
            lblDongHo.setText(time);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(mainWindows.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void openLogin() {
        new LoginJDialog(this,true).setVisible(true);
    }
    
    private void Dimension(JInternalFrame frame) {
        Dimension desktopSize = Desktop.getSize();
        Dimension frameSize = frame.getSize();
        int x = (desktopSize.width - frameSize.width) / 2;
        int y = (desktopSize.height - frameSize.height) / 2;
        frame.setLocation(x, y);
    }
}
